In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('telecom_users.csv')
df.head()

,Unnamed: 0,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,1869,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,4528,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,6344,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6739,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,432,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN

In [3]:
df = df.drop(labels=['Unnamed: 0', 'IDCliente', 'Codigo'], axis=1)
df.head()

,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,ServicoBackupOnline,ProtecaoEquipamento,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn
0,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,SemInternet,SemInternet,SemInternet,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao
1,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,Nao,Sim,Sim,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao
2,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,Nao,Nao,Nao,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim
3,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,Nao,Nao,Nao,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao
4,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,Sim,Nao,Sim,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao

In [4]:
df = df.replace(['Masculino','Sim', 'Fibra', 'Anual', 'BoletoEletronico'], 1)
df = df.replace(['Feminino','Nao','SemInternet', 'SemTelefone', 'Mensal', 'BoletoImpresso'], 0)
df = df.replace(['DSL', '2 anos', 'DebitoAutomatico'],2)
df = df.replace('CartaoCredito',3)

In [5]:
df.count().isnull()

Genero                    False
Aposentado                False
Casado                    False
Dependentes               False
MesesComoCliente          False
ServicoTelefone           False
MultiplasLinhas           False
ServicoInternet           False
ServicoSegurancaOnline    False
ServicoBackupOnline       False
ProtecaoEquipamento       False
ServicoSuporteTecnico     False
ServicoStreamingTV        False
ServicoFilmes             False
TipoContrato              False
FaturaDigital             False
FormaPagamento            False
ValorMensal               False
TotalGasto                False
Churn                     False
dtype: bool

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [7]:
modelo = LinearRegression()

In [8]:
x = df.drop('Churn', axis=1)
y = df['Churn']

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [10]:
modelo.fit(x_train,y_train)

ValueError: could not convert string to float: ''